### ISSUE TITLE
A member can't vote for themselves

### ISSUE THREAD

**Issue by carletex** [carletex/quadratic-diplomacy#10]
It shouldn't be selectable on the "select" contributors screen.

**Comment by carletex** [comment]
As we talked on last meeting, this is not definite yet.

**Comment by eshaan7** [comment]
I found something and I don't know if this is a bug or a feature. So, I am leaving this note here describing the "steps to reproduce" as it seems relevant to this issue.

- I started the application and I got a burner admin user (hereinafter referred to as: my user)
- As a user with only "admin" rights, I couldn't vote but I could add members.
- So, I went into the "Add members" section and added my address as a voter. The transaction went through. Hence, now my user got both "admin" and "voter" rights. See below image.
![image](https://user-images.githubusercontent.com/16389167/130326107-c23806ee-3146-4414-a20c-3d385f8d3c43.png)
- Now that I had "voter" tag, I could vote. So, I went to "Vote" section and allocated all my votes to my "voter" user only that I had added. The transaction went through.
- Then I went to "Reward" and paid all the ETH to my user. The transaction went through and I have no idea how this is possible.

**Comment by carletex** [comment]
Hey @Eshaan7 I think that's a feature (at least for now haha) and it works how it's supposed to work.

But yes, there are some things we should consider:
- Can an user vote for themselves?
- Should we allow payouts if there are members that haven't voted yet?
