### ISSUE TITLE
Single Payment button + update contract (get array of address + amounts to split payout)

### ISSUE THREAD

**Issue by carletex** [carletex/quadratic-diplomacy#6]
Currently, on the **reward** screen, you have to manually reward each member.

### Goal

Create a single "Pay all" button that sends the corresponding ETH to each member. 

We'll need to add a solidity function that gets an array of address and amounts so we can payout everyone with a single tx.

**Comment by over9001** [comment]
This is the feature I'm most interested in seeing, because it prevents mistakes like people accidentally not getting paid out, and it makes admin lives simple. :)

I don't know how to mark an issue as high priority, so I'm just commenting instead.

**Comment by eshaan7** [comment]
Note: I have created 3 new labels for priority. 

![image](https://user-images.githubusercontent.com/16389167/130142250-707ac897-fd5c-477d-97ab-6e61a794ef82.png)

**Comment by eshaan7** [comment]
**Branch:** [`issue#6-single_payment_btn`](https://github.com/carletex/quadratic-diplomacy/commits/issue%236-single_payment_btn).

**Update:**

- I refactored the frontend part of this (https://github.com/carletex/quadratic-diplomacy/commit/5f3d302d6d028ab6258aaaeb1b556ce5fb91b417), not sure about how to do the smart contract stuff yet but I am trying.

**Update 2:**

- I defined a new `payMultiple` payable marked function in the contract. (https://github.com/carletex/quadratic-diplomacy/commit/5755a092af9eedfeda06aa4dbf5d5bdf3f16c371)
- Corresponding change in payments handling logic in frontend (https://github.com/carletex/quadratic-diplomacy/commit/dbbdf21ff7ef58bfb9de8b34e08416650c19cdde).

**Comment by eshaan7** [comment]
Can be closed because https://github.com/moonshotcollective/q-dip/pull/19
